### ISSUE TITLE
problem with create namespace in tenant

### ISSUE THREAD

**Issue by danieljanicki** [projectcapsule/capsule#1196] opened 2024-09-13 13:02 UTC
# Bug description
I prepare capsule:
`$ k get all -n capsule-system
NAME                                              READY   STATUS    RESTARTS   AGE
pod/capsule-controller-manager-67d6cf9ffd-r66cr   1/1     Running   0          23h

NAME                                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/capsule-controller-manager-metrics-service   ClusterIP   172.53.137.101   <none>        8080/TCP   25h
service/capsule-webhook-service                      ClusterIP   172.53.136.55    <none>        443/TCP    25h

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/capsule-controller-manager   1/1     1            1           25h

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/capsule-controller-manager-67d6cf9ffd   1         1         1       23h
replicaset.apps/capsule-controller-manager-798cf964cb   0         0         0       25h
$ k get tnt
NAME       STATE    NAMESPACE QUOTA   NAMESPACE COUNT   NODE SELECTOR   AGE
dev-team   Active                     0                                 22h
oil        Active                     1                                 23h
team-a     Active                     1                                 25h
team-b     Active                     0                                 25h
`

When I try create NS in tenant by yaml:
`apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns
  annotations:
    capsule.clastix.io/tenant: team-a
`
but isn't add NS to TNT.

I try using:
`apiVersion: v1
kind: Namespace
metadata:
  labels:
    capsule.clastix.io/tenant: team-a
    kubernetes.io/metadata.name: oil-production-2
    name: oil-production-2
    capsule.clastix.io/backup: "true"
  name: oil-production-2
  ownerReferences:
  - apiVersion: capsule.clastix.io/v1beta2
    blockOwnerDeletion: true
    controller: true
    kind: Tenant
    name: team-a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

$ k apply -f dj/testing2/new_name_space_in_dev_team_v2.yml
The Namespace "oil-production-2" is invalid: metadata.ownerReferences.uid: Invalid value: "": uid must not be empty`

I can get uid from tnt definition but I need create automatic configuration without create tnt and get uid.

# Logs
`$ kubectl -n capsule-system logs deploy/capsule-controller-manager --since=1h
$
`
# Additional context
`$ capsule --version
capsule: command not found
$ helm list -n capsule-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
capsule capsule-system  2               2024-09-12 13:11:27.716216517 +0000 UTC deployed        capsule-0.7.1   0.7.1
$ kubectl version
Client Version: v1.30.2-eks-1552ad0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2-eks-11a7922
`
- Capsule version: (`capsule --version`)
- Helm Chart version: (`helm list -n capsule-system`)
- Kubernetes version: (`kubectl version`)

**Comment by prometherion** [comment] 2024-09-16 07:27
@danieljanicki I'll share briefly the issue you're facing: Capsule sits on three pillars, such as:

1. User authentication
2. Tenant definition
3. Kubernetes namespaces

You're trying to create Namespaces as an `admin` user and to get them bound to a Tenant which is assigned to users: from the API Server perspective, you're not a Tenant user, and neither you're not directly specifying a Tenant.

I would suggest you by leveraging on user impersonation (`--as` and `--as-group`) or on Tenant prefix support (more info available [here](https://capsule.clastix.io/docs/general/tutorial/#assign-multiple-tenants)).

I'm going to close this issue since it's not a bug, and I'd like to keep it only for confirmed bug reports: any kind of support or help can be obtained using the #capsule Kubernetes Slack workspace channel, or the Discussion section.

**Closed by prometherion** 2024-09-16 07:27 UTC
Labels: invalid
